#pragma config(Motor,  port1,           RightBack,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           RightFront,    tmotorVex393, openLoop)
#pragma config(Motor,  port3,           RightTread,    tmotorVex393, openLoop)
#pragma config(Motor,  port4,           RightWheelTop, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           RightWheelBot, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           LeftWheelTop,  tmotorVex393, openLoop)
#pragma config(Motor,  port7,           LeftWheelBot,  tmotorVex393, openLoop)
#pragma config(Motor,  port8,           LeftTread,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           LeftFront,     tmotorVex393, openLoop)
#pragma config(Motor,  port10,          LeftBack,      tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int wheelRunning = 0;


void drive(){
	motor[RightFront] = vexRT(Ch2);
	motor[RightBack] = vexRT(Ch2);
	motor[LeftFront] = vexRT(Ch3);
	motor[LeftBack] = vexRT(Ch3);
}

void tread(){
motor[RightTread] = -vexRT(Btn6U)*127 + vexRT(Btn6D)*127;
motor[LeftTread] = -vexRT(Btn6U)*127 + vexRT(Btn6D)*127;
}

void wheel(){

if(vexRT(Btn8D) == 1 ){
wheelRunning = 0;
} else if(vexRt(Btn8U)){
wheelRunning = 127;
}

motor[RightWheelTop] =  wheelRunning + vexRT(Btn8R)*127;
motor[RightWheelBot] = wheelRunning + vexRT(Btn8R)*127;
motor[LeftWheelTop] = wheelRunning + vexRT(Btn8R)*127;
motor[LeftWheelBot] = wheelRunning + vexRT(Btn8R)*127;
}

task main()
{
while(true){
drive();
tread();
wheel();
}
}
