#pragma config(Sensor, in1,    selector,       sensorAnalog)
#pragma config(Motor,  port1,           backLeft,      tmotorVex393, openLoop)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port9,           frontRight,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          backRight,     tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "DriverFunctions.h"
#include "SelectorFunctions.h"

task main(){
	clearLCDLine(0);
	clearLCDLine(1);
bLCDBacklight = true;
string text;
while(true){
	//	drive();
if(hasSelectionChanged()){
text = getSelectionNumber()+1;
displayLCDString(0, 0, text);
}
	}
}
